services:

  postgres:
    image: postgres:16-alpine
    container_name: payment_postgres
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER:user}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: payment_redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    networks:
      - payment-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: payment_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - payment-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: payment_kafka
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_HOST_PORT}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:${KAFKA_HOST_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - payment-network

  debezium:
    image: quay.io/debezium/connect:2.5.0.Final
    container_name: payment_debezium
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - kafka
      - postgres
    networks:
      - payment-network

  debezium-setup:
    image: curlimages/curl:latest
    container_name: debezium_setup
    depends_on:
      - debezium
    networks:
      - payment-network
    command: >
      sh -c "
        echo 'Waiting for Debezium...'
        while ! curl -s http://debezium:8083/connectors > /dev/null; do sleep 2; done;
      
        echo 'Cleaning old connectors...'
        curl -X DELETE http://debezium:8083/connectors/payment-outbox-connector
        curl -X DELETE http://debezium:8083/connectors/ledger-outbox-connector
      
        echo 'Registering Payment Connector...'
        curl -i -X POST -H 'Accept:application/json' -H 'Content-Type:application/json' http://debezium:8083/connectors/ -d '{
          \"name\": \"payment-outbox-connector\",
          \"config\": {
            \"connector.class\": \"io.debezium.connector.postgresql.PostgresConnector\",
            \"tasks.max\": \"1\",
            \"database.hostname\": \"postgres\",
            \"database.port\": \"5432\",
            \"database.user\": \"${POSTGRES_USER}\",
            \"database.password\": \"${POSTGRES_PASSWORD}\",
            \"database.dbname\": \"payment_db\",
            \"slot.name\": \"payment_outbox_slot\",
            \"topic.prefix\": \"payment-server\",
            \"plugin.name\": \"pgoutput\",
            \"table.include.list\": \"public.outbox_events\",
            \"tombstones.on.delete\": \"false\",
            \"key.converter\": \"org.apache.kafka.connect.json.JsonConverter\",
            \"key.converter.schemas.enable\": \"false\",
            \"value.converter\": \"org.apache.kafka.connect.json.JsonConverter\",
            \"value.converter.schemas.enable\": \"false\",
            \"transforms\": \"outbox\",
            \"transforms.outbox.type\": \"io.debezium.transforms.outbox.EventRouter\",
            \"transforms.outbox.route.topic.replacement\": \"$${routedByValue}\",
            \"transforms.outbox.table.field.event.id\": \"id\",
            \"transforms.outbox.table.field.event.key\": \"aggregate_id\",
            \"transforms.outbox.table.field.event.type\": \"event_type\",
            \"transforms.outbox.table.field.event.payload\": \"payload\",
            \"transforms.outbox.route.by.field\": \"event_type\",
            \"transforms.outbox.table.expand.json.payload\": \"true\"
          }
        }'
      
        echo 'Registering Ledger Connector...'
        curl -i -X POST -H 'Accept:application/json' -H 'Content-Type:application/json' http://debezium:8083/connectors/ -d '{
          \"name\": \"ledger-outbox-connector\",
          \"config\": {
            \"connector.class\": \"io.debezium.connector.postgresql.PostgresConnector\",
            \"tasks.max\": \"1\",
            \"database.hostname\": \"postgres\",
            \"database.port\": \"5432\",
            \"database.user\": \"${POSTGRES_USER}\",
            \"database.password\": \"${POSTGRES_PASSWORD}\",
            \"database.dbname\": \"ledger_db\",
            \"slot.name\": \"ledger_outbox_slot\",
            \"topic.prefix\": \"ledger-server\",
            \"plugin.name\": \"pgoutput\",
            \"table.include.list\": \"public.outbox_events\",
            \"tombstones.on.delete\": \"false\",
            \"key.converter\": \"org.apache.kafka.connect.json.JsonConverter\",
            \"key.converter.schemas.enable\": \"false\",
            \"value.converter\": \"org.apache.kafka.connect.json.JsonConverter\",
            \"value.converter.schemas.enable\": \"false\",
            \"transforms\": \"outbox\",
            \"transforms.outbox.type\": \"io.debezium.transforms.outbox.EventRouter\",
            \"transforms.outbox.route.topic.replacement\": \"$${routedByValue}\",
            \"transforms.outbox.table.field.event.id\": \"id\",
            \"transforms.outbox.table.field.event.key\": \"aggregate_id\",
            \"transforms.outbox.table.field.event.type\": \"event_type\",
            \"transforms.outbox.table.field.event.payload\": \"payload\",
            \"transforms.outbox.route.by.field\": \"event_type\",
            \"transforms.outbox.table.expand.json.payload\": \"true\"
          }
        }'
      "

volumes:
  postgres_data:
  redis_data:

networks:
  payment-network:
    driver: bridge