spring.application.name=gateway-service

spring.grpc.client.channels.auth-service.address=localhost:9090
+spring.grpc.client.channels.ledger-service.address=localhost:9091
+spring.grpc.client.channels.payment-service.address=localhost:9093