spring.application.name=gateway-service

spring.grpc.client.channels.auth-service.address=localhost:9090
spring.grpc.client.channels.ledger-service.address=localhost:9091
spring.grpc.client.channels.payment-service.address=localhost:9093

spring.data.redis.database=0
spring.data.redis.host=localhost
spring.data.redis.port=${GATEWAY_REDIS_HOST_PORT:6380}
spring.data.redis.password=${GATEWAY_REDIS_PASSWORD}